// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using kolokwium0610.Data;

#nullable disable

namespace kolokwium0610.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250610110014_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("kolokwium0610.Models.Map", b =>
                {
                    b.Property<int>("MapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MapId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MapId");

                    b.ToTable("Map");

                    b.HasData(
                        new
                        {
                            MapId = 1,
                            Name = "Map 1",
                            Type = "stadion"
                        },
                        new
                        {
                            MapId = 2,
                            Name = "Map 2",
                            Type = "boisko"
                        },
                        new
                        {
                            MapId = 3,
                            Name = "Map 3",
                            Type = "stadion"
                        });
                });

            modelBuilder.Entity("kolokwium0610.Models.Match", b =>
                {
                    b.Property<int>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MatchId"));

                    b.Property<decimal?>("BestRating")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric");

                    b.Property<int>("MapId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Team1Score")
                        .HasColumnType("int");

                    b.Property<int>("Team2Score")
                        .HasColumnType("int");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.HasKey("MatchId");

                    b.HasIndex("MapId");

                    b.HasIndex("TournamentId");

                    b.ToTable("Match");

                    b.HasData(
                        new
                        {
                            MatchId = 1,
                            BestRating = 2.4m,
                            MapId = 1,
                            MatchDate = new DateTime(2025, 6, 10, 13, 0, 13, 713, DateTimeKind.Local).AddTicks(7527),
                            Team1Score = 1,
                            Team2Score = 2,
                            TournamentId = 1
                        },
                        new
                        {
                            MatchId = 2,
                            BestRating = 1.4m,
                            MapId = 1,
                            MatchDate = new DateTime(2025, 6, 10, 13, 0, 13, 715, DateTimeKind.Local).AddTicks(3356),
                            Team1Score = 2,
                            Team2Score = 2,
                            TournamentId = 2
                        },
                        new
                        {
                            MatchId = 3,
                            BestRating = 2.8m,
                            MapId = 3,
                            MatchDate = new DateTime(2025, 6, 10, 13, 0, 13, 715, DateTimeKind.Local).AddTicks(3377),
                            Team1Score = 3,
                            Team2Score = 4,
                            TournamentId = 2
                        });
                });

            modelBuilder.Entity("kolokwium0610.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerId"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PlayerId");

                    b.ToTable("Player");

                    b.HasData(
                        new
                        {
                            PlayerId = 1,
                            BirthDate = new DateTime(2025, 6, 10, 13, 0, 13, 715, DateTimeKind.Local).AddTicks(4561),
                            FirstName = "jan",
                            LastName = "kwoal"
                        },
                        new
                        {
                            PlayerId = 2,
                            BirthDate = new DateTime(2025, 6, 10, 13, 0, 13, 715, DateTimeKind.Local).AddTicks(4771),
                            FirstName = "jasdfan",
                            LastName = "kgdfwoal"
                        },
                        new
                        {
                            PlayerId = 3,
                            BirthDate = new DateTime(2025, 6, 10, 13, 0, 13, 715, DateTimeKind.Local).AddTicks(4778),
                            FirstName = "sdf",
                            LastName = "asd"
                        });
                });

            modelBuilder.Entity("kolokwium0610.Models.Player_Match", b =>
                {
                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("MVPs")
                        .HasColumnType("int");

                    b.Property<decimal>("Rating")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric");

                    b.HasKey("MatchId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Player_Match");

                    b.HasData(
                        new
                        {
                            MatchId = 1,
                            PlayerId = 1,
                            MVPs = 8,
                            Rating = 2.8m
                        },
                        new
                        {
                            MatchId = 2,
                            PlayerId = 2,
                            MVPs = 4,
                            Rating = 3.8m
                        },
                        new
                        {
                            MatchId = 3,
                            PlayerId = 3,
                            MVPs = 32,
                            Rating = 5.8m
                        });
                });

            modelBuilder.Entity("kolokwium0610.Models.Tournament", b =>
                {
                    b.Property<int>("TournamentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TournamentId"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TournamentId");

                    b.ToTable("Tournament");

                    b.HasData(
                        new
                        {
                            TournamentId = 1,
                            EndDate = new DateTime(2025, 6, 10, 13, 0, 13, 715, DateTimeKind.Local).AddTicks(5939),
                            Name = "mistrzostwa1",
                            StartDate = new DateTime(2025, 6, 10, 13, 0, 13, 715, DateTimeKind.Local).AddTicks(5745)
                        },
                        new
                        {
                            TournamentId = 2,
                            EndDate = new DateTime(2025, 6, 10, 13, 0, 13, 715, DateTimeKind.Local).AddTicks(6132),
                            Name = "mistrzostwa2",
                            StartDate = new DateTime(2025, 6, 10, 13, 0, 13, 715, DateTimeKind.Local).AddTicks(6126)
                        },
                        new
                        {
                            TournamentId = 3,
                            EndDate = new DateTime(2025, 6, 10, 13, 0, 13, 715, DateTimeKind.Local).AddTicks(6135),
                            Name = "mistrzostwa3",
                            StartDate = new DateTime(2025, 6, 10, 13, 0, 13, 715, DateTimeKind.Local).AddTicks(6133)
                        });
                });

            modelBuilder.Entity("kolokwium0610.Models.Match", b =>
                {
                    b.HasOne("kolokwium0610.Models.Map", "Map")
                        .WithMany("Matches")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("kolokwium0610.Models.Tournament", "Tournament")
                        .WithMany("Matches")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Map");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("kolokwium0610.Models.Player_Match", b =>
                {
                    b.HasOne("kolokwium0610.Models.Match", "Match")
                        .WithMany("Player_Matches")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("kolokwium0610.Models.Player", "Player")
                        .WithMany("Player_Matches")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("kolokwium0610.Models.Map", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("kolokwium0610.Models.Match", b =>
                {
                    b.Navigation("Player_Matches");
                });

            modelBuilder.Entity("kolokwium0610.Models.Player", b =>
                {
                    b.Navigation("Player_Matches");
                });

            modelBuilder.Entity("kolokwium0610.Models.Tournament", b =>
                {
                    b.Navigation("Matches");
                });
#pragma warning restore 612, 618
        }
    }
}
